Front\YxBundle\Entity\Genres:
    type: entity
    table: genres
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        gname:
            type: string
            length: 255
            fixed: false
            nullable: false
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: true
        image:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
