Front\YxBundle\Entity\Jokecategories:
    type: entity
    table: jokecategories
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        catname:
            type: string
            length: 255
            fixed: false
            nullable: false
        pcatid:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
