Front\YxBundle\Entity\Newscontents:
    type: entity
    table: newscontents
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        description:
            type: string
            length: 255
            fixed: false
            nullable: false
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
