Front\YxBundle\Entity\Tellafriends:
    type: entity
    table: tellafriends
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: integer
            unsigned: false
            nullable: false
            column: user_id
        friendemailadd:
            type: string
            length: 225
            fixed: false
            nullable: false
        status:
            type: string
            length: null
            fixed: false
            nullable: false
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
