Front\YxBundle\Entity\Users:
    type: entity
    table: users
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        firstname:
            type: string
            length: 30
            fixed: false
            nullable: true
        lastname:
            type: string
            length: 30
            fixed: false
            nullable: true
        gender:
            type: string
            length: null
            fixed: false
            nullable: false
        address:
            type: string
            length: 50
            fixed: false
            nullable: true
        city:
            type: string
            length: 50
            fixed: false
            nullable: true
        state:
            type: string
            length: 50
            fixed: false
            nullable: true
        countryId:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: country_id
        zip:
            type: string
            length: 10
            fixed: false
            nullable: true
        mobilephone:
            type: string
            length: 20
            fixed: false
            nullable: true
        carrier:
            type: string
            length: 255
            fixed: false
            nullable: false
        workphone:
            type: string
            length: 20
            fixed: false
            nullable: true
        email:
            type: string
            length: 50
            fixed: false
            nullable: true
        apiUserId:
            type: string
            length: 70
            fixed: false
            nullable: true
            column: api_user_id
        password:
            type: string
            length: 10
            fixed: false
            nullable: false
        birthdate:
            type: date
            nullable: true
        status:
            type: string
            length: null
            fixed: false
            nullable: false
        activationkey:
            type: string
            length: 32
            fixed: false
            nullable: false
        created:
            type: datetime
            nullable: true
        modified:
            type: datetime
            nullable: true
        dateSendJoke:
            type: date
            nullable: true
            column: date_send_joke
        dateSendRing:
            type: date
            nullable: true
            column: date_send_ring
        countJoke:
            type: integer
            unsigned: false
            nullable: false
            column: count_joke
        countRing:
            type: integer
            unsigned: false
            nullable: false
            column: count_ring
        deliveryType:
            type: integer
            unsigned: false
            nullable: true
            column: delivery_type
        dateSubscript:
            type: date
            nullable: true
            column: date_subscript
        idSubscript:
            type: integer
            unsigned: false
            nullable: false
            column: id_subscript
    lifecycleCallbacks: {  }
