Front\YxBundle\Entity\Useramounts:
    type: entity
    table: useramounts
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: integer
            unsigned: false
            nullable: false
            column: user_id
        amount:
            type: float
            nullable: false
        balance:
            type: float
            nullable: false
        status:
            type: string
            length: null
            fixed: false
            nullable: false
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
