Front\YxBundle\Entity\Wishes:
    type: entity
    table: wishes
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: user_id
        ringtoneId:
            type: integer
            unsigned: false
            nullable: true
            column: ringtone_id
        songId:
            type: integer
            unsigned: false
            nullable: true
            column: song_id
        created:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
