Front\YxBundle\Entity\Yomamma:
    type: entity
    table: yomamma
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        description:
            type: string
            length: 255
            fixed: false
            nullable: false
        ringtone:
            type: string
            length: 255
            fixed: false
            nullable: false
        date:
            type: date
            nullable: false
        status:
            type: boolean
            nullable: false
        type:
            type: string
            length: 1
            fixed: true
            nullable: false
        price:
            type: string
            length: 11
            fixed: false
            nullable: false
        myxerTag:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: myxer_tag
        category:
            type: integer
            unsigned: false
            nullable: false
        statPc:
            type: integer
            unsigned: false
            nullable: false
            column: stat_pc
        statPhone:
            type: integer
            unsigned: false
            nullable: false
            column: stat_phone
        prewRingtone:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: prew_ringtone
    lifecycleCallbacks: {  }
